package com.bridgecrew.utils

val CHECKNAMEDEPTH = 4
val POLICYDETAILS = "Policy Details:"
val GUIDELINES_TITLE = "View Guidelines"
val CUSTOM_GUIDELINES_TITLE = "Guidelines:"

object PANELTYPE {
    val AUTO_CHOOSE_PANEL = 0
    val CHECKOV_SCAN_FINISHED_EMPTY = 1
    val CHECKOV_SCAN_FINISHED = 2
    val CHECKOV_SCAN_STARTED = 3
    val CHECKOV_SCAN_ERROR = 4
    val CHECKOV_PRE_SCAN = 5
    val CHECKOV_SCAN_PARSING_ERROR = 6
    val CHECKOV_INSTALATION_STARTED = 7
}
val DEFAULT_TIMEOUT: Long = 30000