package com.bridgecrew.utils

val CHECKNAMEDEPTH = 4
val POLICYDETAILS = "Policy Details:"

object PANELTYPE {
    val AUTOCHOOSEPANEL = 0
    val CHECKOVFINISHED = 1
    val CHECKOVSTARTED = 2
    val CHECKOVERROR = 3
    val CHECKOVPRERSCAN = 4
    val CHECKOVPARSINGERROR = 5
    val CHECKOVINSTALATION = 6
}
val DEFAULT_TIMEOUT: Long = 30000